### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [sciguy14/Exploring-Arduino-2nd-Edition#1]
Hi, I noticed that in your repositories there is always a `while(Wire.available() == 0);` after a Wire.requestFrom(). You may remove all those lines with `while(Wire.available() == 0);` (11 times).

Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by sciguy14** [comment]
Thanks for the catch @Koepel ! And that's a very nice Wiki resource that you've put together.
While you're right that the use of the Wire.available() can be removed, blocking of the remainder of the program execution was intentional. In these sketches, the whole point of the programs are to report temperature, and they don't really do anything useful if the temperature sensor doesn't return any data. However, the failure mode of the program simply stopping may be confusing for beginning users, so I'm going to make a change to check the returned number of bytes from `Wire.requestFrom()`, print an error message if it is zero, and then halt the program execution.

**Comment by Koepel** [comment]
I prefer to check if the number of requested bytes is the same as the number of received bytes. Either with the return value of Wire.requestFrom() or with a single call to Wire.available().
At this moment that is the same as checking for zero (or non-zero), since the Wire library returns zero if it detects a problem on the I2C bus.

**Comment by sciguy14** [comment]
Is your preference for doing that to handle multi-byte requests that might return incomplete data? In the examples that I've just updated, they are all single byte requests. As far as I'm aware, the only conceivable values that could be returned by Wire.requestFrom() are `0` or `1` when a request for a single byte is made. Thus, in my examples, halting to an error on the return value being equal to zero is functionally equivalent to checking that the return value is not equal to 1.

**Comment by Koepel** [comment]
Yes, I meant for multi-byte requests. For a single byte it is 0 or 1 of course.

**Comment by sciguy14** [comment]
Ok - understood. Will keep that in mind for any multi-byte reads that I do in the future!
