### ISSUE TITLE
Chapter 14, reading file not working (gives 0ms instead of 1000)

### ISSUE THREAD

**Issue by avlapp** [sciguy14/Exploring-Arduino-2nd-Edition#5]
Chapter 14, reading file not working (gives 0ms instead of 1000)

Is there some code missing? I see in your video, you're fiddling with some extra code

https://youtu.be/5v5A3j7Rrco?t=826

**Comment by avlapp** [comment]
Changing while to if seems to fix it


    if (commandFile.available())


```
//Read the configuration information (speed.txt)
  File commandFile = SD.open("speed.txt");
  if (commandFile)
  {
     Serial.println("Reading Command File");
  
    if (commandFile.available())
     {
       refresh_rate = commandFile.parseInt();
       //refresh_rate = 1000;
     }
     Serial.print("Refresh Rate = ");
     Serial.print(refresh_rate);
     Serial.println("ms");
     commandFile.close(); //Close the file when finished
  }  
  else
  {
    Serial.println("Could not read command file.");
    Serial.print("Will use default refresh rate of ");
    Serial.print(refresh_rate);
    Serial.println("ms!");
  } 

```

**Comment by sciguy14** [comment]
@avlap The video you posted is from a 2011 tutorial. The methods for reading numbers from files has improved dramatically since I first posted that video. That is why the code from the book is different (and shorter). The `parseInt()` function basically does everything that previously had to be done discreetly to get an integer out of a text file.

The original `while()` that my code has _should_ work as long as the refresh rate value is the ONLY thing you have written in that file, as is described in the book. The `parseInt()` function will read digits until it encounters a non-digit. That non digit should be the end of the file. I suspect the reason it didn't work for you is that you have a newline after your refresh rate entry. Because of that newline, the file stream still has "available" content and the while loop executes again. When the while loops executes a second time, it looks for integers that occur on the line after your first line. It fails to find any in the timeout window, and returns a zero instead (you can see on the documentation page that a zero will be returned if an integer is not found): https://www.arduino.cc/en/Reference/parseInt

Your approach works as well. By changing to an `if()` statement, you made it so that the `parseInt()` will only run on the first line of the file and then use that value, ignoring any newlines or other data that you might have in the file after the first integer.

I will close this ticket, but feel free to re-open if you have further questions!
